// Habilidades oficiais da BNCC (Ensino Fundamental - Anos Iniciais).
// Subconjunto curado para 1º ao 5º ano, Língua Portuguesa e Matemática.
// Códigos e descrições conforme a Base Nacional Comum Curricular (MEC, 2018).
export const BNCC = [
  // ---------------- MATEMÁTICA ----------------
  ["EF01MA01", "MAT", 1, "Números", "Contagem de rotina e de quantidades",
    "Utilizar números naturais como indicador de quantidade ou de ordem em diferentes situações cotidianas e reconhecer situações em que os números não indicam contagem nem ordem, mas sim código de identificação."],
  ["EF01MA02", "MAT", 1, "Números", "Quantificação de elementos de uma coleção",
    "Contar de maneira exata ou aproximada, utilizando diferentes estratégias como o pareamento e outros agrupamentos."],
  ["EF01MA04", "MAT", 1, "Números", "Leitura, escrita e comparação de números naturais",
    "Contar a quantidade de objetos de coleções até 100 unidades e apresentar o resultado por registros verbais e simbólicos, em situações de seu interesse, como jogos, brincadeiras, materiais da sala de aula, entre outros."],
  ["EF01MA06", "MAT", 1, "Números", "Construção de fatos básicos da adição",
    "Construir fatos básicos da adição e utilizá-los em procedimentos de cálculo para resolver problemas."],
  ["EF01MA08", "MAT", 1, "Números", "Problemas de adição e subtração",
    "Resolver e elaborar problemas de adição e de subtração, envolvendo números de até dois algarismos, com os significados de juntar, acrescentar, separar e retirar, com o suporte de imagens e/ou material manipulável, utilizando estratégias e formas de registro pessoais."],
  ["EF01MA14", "MAT", 1, "Geometria", "Figuras geométricas espaciais",
    "Identificar e nomear figuras planas (círculo, quadrado, retângulo e triângulo) em desenhos apresentados em diferentes disposições ou em contornos de faces de sólidos geométricos."],

  ["EF02MA01", "MAT", 2, "Números", "Leitura, escrita, comparação e ordenação de números",
    "Comparar e ordenar números naturais (até a ordem de centenas) pela compreensão de características do sistema de numeração decimal (valor posicional e função do zero)."],
  ["EF02MA05", "MAT", 2, "Números", "Construção de fatos fundamentais da adição e da subtração",
    "Construir fatos básicos da adição e subtração e utilizá-los no cálculo mental ou escrito."],
  ["EF02MA06", "MAT", 2, "Números", "Problemas de adição e de subtração",
    "Resolver e elaborar problemas de adição e de subtração, envolvendo números de até três ordens, com os significados de juntar, acrescentar, separar, retirar, utilizando estratégias pessoais."],
  ["EF02MA07", "MAT", 2, "Números", "Problemas de multiplicação",
    "Resolver e elaborar problemas de multiplicação (por 2, 3, 4 e 5) com a ideia de adição de parcelas iguais por meio de estratégias e formas de registro pessoais, utilizando ou não suporte de imagens e/ou material manipulável."],
  ["EF02MA20", "MAT", 2, "Probabilidade e estatística", "Coleta, classificação e representação de dados",
    "Comparar informações de pesquisas apresentadas por meio de tabelas de dupla entrada e em gráficos de colunas simples ou barras, para melhor compreender aspectos da realidade próxima."],

  ["EF03MA01", "MAT", 3, "Números", "Leitura, escrita, comparação e ordenação de números naturais",
    "Ler, escrever e comparar números naturais de até a ordem de unidade de milhar, estabelecendo relações entre os registros numéricos e em língua materna."],
  ["EF03MA03", "MAT", 3, "Números", "Composição e decomposição de números naturais",
    "Construir e utilizar fatos básicos da adição e da multiplicação para o cálculo mental ou escrito."],
  ["EF03MA07", "MAT", 3, "Números", "Problemas de multiplicação",
    "Resolver e elaborar problemas de multiplicação (por 2, 3, 4, 5 e 10) com os significados de adição de parcelas iguais e elementos apresentados em disposição retangular, utilizando diferentes estratégias de cálculo e registros."],
  ["EF03MA08", "MAT", 3, "Números", "Problemas de divisão",
    "Resolver e elaborar problemas de divisão de um número natural por outro (até 10), com resto zero e com resto diferente de zero, com os significados de repartição equitativa e de medida, por meio de estratégias e registros pessoais."],
  ["EF03MA17", "MAT", 3, "Grandezas e medidas", "Significado de medida e de unidade de medida",
    "Reconhecer que o resultado de uma medida depende da unidade de medida utilizada."],

  ["EF04MA01", "MAT", 4, "Números", "Sistema de numeração decimal",
    "Ler, escrever e ordenar números naturais até a ordem de dezenas de milhar."],
  ["EF04MA06", "MAT", 4, "Números", "Problemas de multiplicação",
    "Resolver e elaborar problemas envolvendo diferentes significados da multiplicação (adição de parcelas iguais, organização retangular e proporcionalidade), utilizando estratégias diversas, como cálculo por estimativa, cálculo mental e algoritmos."],
  ["EF04MA07", "MAT", 4, "Números", "Problemas de divisão",
    "Resolver e elaborar problemas de divisão cujo divisor tenha no máximo dois algarismos, envolvendo os significados de repartição equitativa e de medida, utilizando estratégias diversas, como cálculo por estimativa, cálculo mental e algoritmos."],
  ["EF04MA09", "MAT", 4, "Números", "Números racionais: frações unitárias",
    "Reconhecer as frações unitárias mais usuais (1/2, 1/3, 1/4, 1/5, 1/10 e 1/100) como unidades de medida menores do que uma unidade, utilizando a reta numérica como recurso."],
  ["EF04MA20", "MAT", 4, "Grandezas e medidas", "Medidas de tempo",
    "Medir e estimar comprimentos (incluindo perímetros), massas e capacidades, utilizando unidades de medida padronizadas mais usuais, valorizando e respeitando a cultura local."],

  ["EF05MA01", "MAT", 5, "Números", "Sistema de numeração decimal",
    "Ler, escrever e ordenar números naturais até a ordem das centenas de milhar com compreensão das principais características do sistema de numeração decimal."],
  ["EF05MA02", "MAT", 5, "Números", "Números racionais na forma decimal",
    "Ler, escrever e ordenar números racionais na forma decimal com compreensão das principais características do sistema de numeração decimal, utilizando, como recursos, a composição e decomposição e a reta numérica."],
  ["EF05MA03", "MAT", 5, "Números", "Representação fracionária",
    "Identificar e representar frações (menores e maiores que a unidade), associando-as ao resultado de uma divisão ou à ideia de parte de um todo, utilizando a reta numérica como recurso."],
  ["EF05MA07", "MAT", 5, "Números", "Problemas com números racionais",
    "Resolver e elaborar problemas de adição e subtração com números naturais e com números racionais, cuja representação decimal seja finita, utilizando estratégias diversas, como cálculo por estimativa, cálculo mental e algoritmos."],
  ["EF05MA08", "MAT", 5, "Números", "Problemas de multiplicação e divisão com racionais",
    "Resolver e elaborar problemas de multiplicação e divisão com números naturais e com números racionais cuja representação decimal é finita (com multiplicador natural e divisor natural e diferente de zero), utilizando estratégias diversas, como cálculo por estimativa, cálculo mental e algoritmos."],
  ["EF05MA24", "MAT", 5, "Probabilidade e estatística", "Leitura e interpretação de dados",
    "Interpretar dados estatísticos apresentados em textos, tabelas e gráficos (colunas ou linhas), referentes a outras áreas do conhecimento ou a outros contextos, como saúde e trânsito, e produzir textos com o objetivo de sintetizar conclusões."],

  // ---------------- LÍNGUA PORTUGUESA ----------------
  ["EF01LP01", "LP", 1, "Análise linguística/semiótica (Alfabetização)", "Protocolos de leitura",
    "Reconhecer que textos são lidos e escritos da esquerda para a direita e de cima para baixo da página."],
  ["EF01LP02", "LP", 1, "Análise linguística/semiótica (Alfabetização)", "Construção do sistema alfabético",
    "Escrever, espontaneamente ou por ditado, palavras e frases de forma alfabética – usando letras/grafemas que representem fonemas."],
  ["EF01LP08", "LP", 1, "Análise linguística/semiótica (Alfabetização)", "Correspondência fonema-grafema",
    "Relacionar elementos sonoros (sílabas, fonemas, partes de palavras) com sua representação escrita."],
  ["EF15LP03", "LP", 1, "Leitura/escuta (campos de atuação - todos)", "Estratégias de leitura",
    "Localizar informações explícitas em textos."],

  ["EF02LP01", "LP", 2, "Análise linguística/semiótica (Alfabetização)", "Construção do sistema alfabético e da ortografia",
    "Utilizar, ao produzir o texto, grafia correta de palavras conhecidas ou com estruturas silábicas já dominadas, letras maiúsculas em início de frases e em substantivos próprios, segmentação entre as palavras, ponto final, ponto de interrogação e ponto de exclamação."],
  ["EF02LP07", "LP", 2, "Análise linguística/semiótica (Alfabetização)", "Segmentação de palavras e classificação",
    "Escrever palavras, frases, textos curtos nas formas imprensa e cursiva."],
  ["EF12LP04", "LP", 2, "Leitura/escuta (campo da vida cotidiana)", "Leitura de textos instrucionais",
    "Ler e compreender, em colaboração com os colegas e com a ajuda do professor ou já com certa autonomia, listas, agendas, calendários, avisos, convites, receitas, instruções de montagem (digitais ou impressos), dentre outros gêneros do campo da vida cotidiana, considerando a situação comunicativa e o tema/assunto do texto e relacionando sua forma de organização à sua finalidade."],

  ["EF03LP01", "LP", 3, "Análise linguística/semiótica", "Construção do sistema alfabético e da ortografia",
    "Ler e escrever palavras com correspondências regulares contextuais entre grafemas e fonemas – c/qu; g/gu; r/rr; s/ss; o (e não u) e e (e não i) em sílaba átona em final de palavra – e com marcas de nasalidade (til, m, n)."],
  ["EF35LP03", "LP", 3, "Leitura/escuta (campos de atuação - todos)", "Estratégias de leitura: compreensão global",
    "Identificar a ideia central do texto, demonstrando compreensão global."],
  ["EF35LP04", "LP", 4, "Leitura/escuta (campos de atuação - todos)", "Estratégias de leitura: inferências",
    "Inferir informações implícitas nos textos lidos."],
  ["EF35LP05", "LP", 4, "Leitura/escuta (campos de atuação - todos)", "Estratégias de leitura: vocabulário",
    "Inferir o sentido de palavras ou expressões desconhecidas em textos, com base no contexto da frase ou do texto."],
  ["EF04LP01", "LP", 4, "Análise linguística/semiótica", "Construção do sistema alfabético e da ortografia",
    "Grafar palavras utilizando regras de correspondência fonema-grafema regulares diretas e contextuais."],
  ["EF05LP01", "LP", 5, "Análise linguística/semiótica", "Construção do sistema alfabético e da ortografia",
    "Grafar palavras utilizando regras de correspondência fonema-grafema regulares, contextuais e morfológicas e palavras de uso frequente com correspondências irregulares."],
  ["EF05LP08", "LP", 5, "Análise linguística/semiótica", "Morfossintaxe",
    "Diferenciar palavras primitivas, derivadas e compostas, e derivadas por adição de prefixo e de sufixo."],
  ["EF05LP22", "LP", 5, "Leitura/escuta (campo das práticas de estudo e pesquisa)", "Compreensão em leitura",
    "Ler e compreender verbetes de dicionário, identificando a estrutura, as informações gramaticais (significado de abreviaturas) e as informações semânticas."],
];

export const SUBJECTS = [
  ["LP", "Língua Portuguesa"],
  ["MAT", "Matemática"],
  ["CIE", "Ciências"],
  ["HIS", "História"],
  ["GEO", "Geografia"],
];
